sudo: required
language: node_js
node_js:
  - 4.4.0
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install docker-engine
  - make install
  - make build
  - make run-debug
script:
  - make test