# ezmaster docker-compose dedicated for development
version: '3.4'

services:

  ezmaster-api:
    container_name: ezmaster-api
    image: inistcnrs/ezmaster-api:3.8.2
    build:
      context: ./ezmaster-api
      args:
        - http_proxy
        - https_proxy
    volumes:
      - ./ezmaster-api:/app
      - ./data/applications:/app/data/applications
      - ./data/instances:/app/data/instances
      - ./data/manifests:/app/data/manifests
      - /var/run/docker.sock:/var/run/docker.sock
      - ezmaster-rp-nginx-data:/etc/nginx/conf.d/
      - ./ezmaster-rp/ezmaster-instance-nginx.conf.tpl:/etc/nginx/conf.d/ezmaster-instance-nginx.conf.tpl
    working_dir: /app
    environment:
      EZMASTER_USER: ${EZMASTER_USER}
      EZMASTER_PASSWORD: ${EZMASTER_PASSWORD}      
      EZMASTER_PUBLIC_IP : ${EZMASTER_PUBLIC_IP}
      EZMASTER_FREE_PORT_RANGE : ${EZMASTER_FREE_PORT_RANGE}
      EZMASTER_PUBLIC_DOMAIN: ${EZMASTER_PUBLIC_DOMAIN}
      EZMASTER_PATH: ${PWD}
      EZMASTER_FULL_FS_PERCENT: ${EZMASTER_FULL_FS_PERCENT}
      NODE_ENV: "development"
      DEBUG: ${DEBUG}
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    ports:
      - 35269:35269
    command: npm run start-debug
    networks:
      - eznetwork


  ezmaster-front:
    container_name: ezmaster-front
    image: inistcnrs/ezmaster-front:3.8.2
    build:
      context: ./ezmaster-front
      args:
        - http_proxy
        - https_proxy
    environment:
      EZMASTER_USER: ${EZMASTER_USER}
      EZMASTER_PASSWORD: ${EZMASTER_PASSWORD}
    volumes:
      - ./ezmaster-front/nginx.debug.conf:/etc/nginx/nginx.conf.orig
    links:
      - ezmaster-api
      - ezmaster-front-debug
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    ports:
      - 35268:35268
    networks:
      - eznetwork

  ezmaster-front-debug:
    container_name: ezmaster-front-debug
    image: node:8.9.0
    volumes:
      - ./ezmaster-front:/app
    working_dir: /app
    environment:
      NODE_ENV: "development"
      DEBUG: ${DEBUG}
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    command: npm run start
    networks:
      - eznetwork


  ezmaster-rp:
    container_name: ezmaster-rp
    image: inistcnrs/ezmaster-rp:3.8.2
    build:
      context: ./ezmaster-rp
      args:
        - http_proxy
        - https_proxy
    volumes:
      - ./ezmaster-rp/index.html:/app/public/index.html
      - ./ezmaster-rp/entrypoint.sh:/entrypoint.sh
      - ./ezmaster-rp/nginx.conf:/etc/nginx/nginx.conf
      - ./ezmaster-rp/ezmaster-instance-nginx.conf.tpl:/etc/nginx/conf.d/ezmaster-instance-nginx.conf.tpl
      - ezmaster-rp-nginx-data:/etc/nginx/conf.d/
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    ports:
      - 35267:80
    networks:
      - eznetwork


  ezmaster-webdav:
    container_name: ezmaster-webdav
    image: inistcnrs/ezmaster-webdav:3.8.2
    build:
      context: ./ezmaster-webdav
      args:
        - http_proxy
        - https_proxy
    volumes:
      - ./data/instances:/media
      - ./ezmaster-webdav/nginx.conf:/etc/nginx/nginx.conf.orig
    environment:
      EZMASTER_USER: ${EZMASTER_USER}
      EZMASTER_PASSWORD: ${EZMASTER_PASSWORD}
    ports:
      - 35270:35270
    networks:
      - eznetwork

networks:
  eznetwork:
    driver: bridge

# shared volume used to exchange nginx
# vhost config for dynamic ezmaster's instances
volumes:
  ezmaster-rp-nginx-data: