# ezmaster docker-compose dedicated for development
version: '2'

services:

  ezmaster-api:
    container_name: ezmaster-api
    image: inistcnrs/ezmaster-api:3.8.2
    build:
      context: ./ezmaster-api
      args:
        - http_proxy
        - https_proxy
    links: # to remove
      - ezmaster_db # to remove
    volumes:
      - ./ezmaster-api:/app
      - ./data/applications:/app/data/applications
      - ./data/instances:/app/data/instances
      - ./data/manifests:/app/data/manifests
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    environment:
      EZMASTER_USER: ${EZMASTER_USER}
      EZMASTER_PASSWORD: ${EZMASTER_PASSWORD}      
      EZMASTER_MONGODB_HOST_PORT: "ezmaster_db:27017" # to remove
      EZMASTER_PUBLIC_IP : ${EZMASTER_PUBLIC_IP}
      EZMASTER_FREE_PORT_RANGE : ${EZMASTER_FREE_PORT_RANGE}
      EZMASTER_PUBLIC_DOMAIN: ${EZMASTER_PUBLIC_DOMAIN}
      EZMASTER_PATH: ${PWD}
      EZMASTER_FULL_FS_PERCENT: ${EZMASTER_FULL_FS_PERCENT}
      NODE_ENV: "development"
      DEBUG: ${DEBUG}
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    ports:
      - 35269:35267
    command: npm run start-debug
    networks:
      - eznetwork


  ezmaster-front:
    container_name: ezmaster-front
    image: node:8.4.0
    volumes:
      - ./ezmaster-front:/app
    working_dir: /app
    environment:
      NODE_ENV: "development"
      DEBUG: ${DEBUG}
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    ports:
      - 35268:35268
    command: npm run start
    networks:
      - eznetwork


  ezmaster-rp:
    container_name: ezmaster-rp
    image: inistcnrs/ezmaster-rp:3.8.2
    build:
      context: ./ezmaster-rp
      args:
        - http_proxy
        - https_proxy
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    ports:
      - 35267:80
    networks:
      - eznetwork


  ezmaster-webdav:
    container_name: ezmaster-webdav
    image: inistcnrs/ezmaster-webdav:3.8.2
    build:
      context: ./ezmaster-webdav
      args:
        - http_proxy
        - https_proxy
    volumes:
      - ./data/instances:/media
      - ./ezmaster-webdav/nginx.conf:/etc/nginx/nginx.conf
    environment:
      EZMASTER_USER: ${EZMASTER_USER}
      EZMASTER_PASSWORD: ${EZMASTER_PASSWORD}
    ports:
      - 35270:8080
    networks:
      - eznetwork

  ezmaster_db:
    container_name: ezmaster_db
    image: mongo:3.4.1
    ports:
      - 27017:27017
    command: --smallfiles
    networks:
      - eznetwork

networks:
  eznetwork:
    driver: bridge
